site_name: Future Systems Lab Docs
theme:
  name: material
  palette:
    primary: blue
    accent: teal

nav:
  - Overview: docs/index.md
  - Architecture:
      - Blockchain Layer: architecture/Blockchain-Layer.md
      - Security & Privacy Layer: architecture/Security-Privacy-Layer.md
      - Data Layer: architecture/Data-Layer.md
      - Wearables & Sensor Layer: architecture/Wearables-Sensor-Layer.md
